//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTable.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTable.Net.Properties.InternalResources", typeof(InternalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding item &apos;{0}&apos;.
        /// </summary>
        internal static string AddingItem {
            get {
                return ResourceManager.GetString("AddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closed.
        /// </summary>
        internal static string ApplicationClosed {
            get {
                return ResourceManager.GetString("ApplicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        internal static string ApplicationStarted {
            get {
                return ResourceManager.GetString("ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application terminated.
        /// </summary>
        internal static string ApplicationTerminated {
            get {
                return ResourceManager.GetString("ApplicationTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ArithmeticType member: {0}..
        /// </summary>
        internal static string ArithmeticTypeUnknownMember {
            get {
                return ResourceManager.GetString("ArithmeticTypeUnknownMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association exists.
        /// </summary>
        internal static string AssociationExists {
            get {
                return ResourceManager.GetString("AssociationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association doesn&apos;t exist.
        /// </summary>
        internal static string AssociationNotExists {
            get {
                return ResourceManager.GetString("AssociationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        internal static string BinExtension {
            get {
                return ResourceManager.GetString("BinExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer will exceed its size (count: {0}, current size: {1}).
        /// </summary>
        internal static string BufferWillExceedItsSize {
            get {
                return ResourceManager.GetString("BufferWillExceedItsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BytesCount is not specified..
        /// </summary>
        internal static string BytesCountNotSpecified {
            get {
                return ResourceManager.GetString("BytesCountNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X2.
        /// </summary>
        internal static string ByteToHexFormat {
            get {
                return ResourceManager.GetString("ByteToHexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing buffer size from {0} to {1}.
        /// </summary>
        internal static string ChangingBufferSize {
            get {
                return ResourceManager.GetString("ChangingBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing settings from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string ChangingSettingsFromTo {
            get {
                return ResourceManager.GetString("ChangingSettingsFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if association exists.
        /// </summary>
        internal static string CheckingIfAssociationExists {
            get {
                return ResourceManager.GetString("CheckingIfAssociationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking existance of key &apos;{0}&apos;.
        /// </summary>
        internal static string CheckingKeyExistance {
            get {
                return ResourceManager.GetString("CheckingKeyExistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the buffer.
        /// </summary>
        internal static string ClearingBuffer {
            get {
                return ResourceManager.GetString("ClearingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing recent files list.
        /// </summary>
        internal static string ClearingRecentFilesList {
            get {
                return ResourceManager.GetString("ClearingRecentFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:datatable.net@blackbox82.org.
        /// </summary>
        internal static string ContactEmailLink {
            get {
                return ResourceManager.GetString("ContactEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string CountValueName {
            get {
                return ResourceManager.GetString("CountValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created FileAssociation object for &apos;{0}&apos; extension.
        /// </summary>
        internal static string CreatedFileAssociation {
            get {
                return ResourceManager.GetString("CreatedFileAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating or opening key &apos;{0}&apos;.
        /// </summary>
        internal static string CreatingOrOpeningKey {
            get {
                return ResourceManager.GetString("CreatingOrOpeningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating and opening subkey &apos;{0}&apos; for key &apos;{1}&apos;.
        /// </summary>
        internal static string CreatingOrOpeningSubkey {
            get {
                return ResourceManager.GetString("CreatingOrOpeningSubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture is {0}.
        /// </summary>
        internal static string CurrentCulture {
            get {
                return ResourceManager.GetString("CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current row index {0} is too big for row count {1}.
        /// </summary>
        internal static string CurrentRowIndexIsTooBigForRowCount {
            get {
                return ResourceManager.GetString("CurrentRowIndexIsTooBigForRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current UI culture is {0}.
        /// </summary>
        internal static string CurrentUICulture {
            get {
                return ResourceManager.GetString("CurrentUICulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error.
        /// </summary>
        internal static string DataError {
            get {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data line items count {0} doesn&apos;t match column count {1}.
        /// </summary>
        internal static string DataLineItemsCountDoesNotMatchColumnCount {
            get {
                return ResourceManager.GetString("DataLineItemsCountDoesNotMatchColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arguments: {0}, number of functions: {1}, agruments type: {2}, functions type: {3}, arithmetic type: {4}, argument scales: {5}, function scales: {6}.
        /// </summary>
        internal static string DataPropertiesDtoScalesToStringFormat {
            get {
                return ResourceManager.GetString("DataPropertiesDtoScalesToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arguments: {0}, number of functions: {1}, agruments type: {2}, functions type: {3}, arithmetic type: {4}.
        /// </summary>
        internal static string DataPropertiesDtoToStringFormat {
            get {
                return ResourceManager.GetString("DataPropertiesDtoToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DataType member: {0}.
        /// </summary>
        internal static string DataTypeUnknownMember {
            get {
                return ResourceManager.GetString("DataTypeUnknownMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was loaded successfully.
        /// </summary>
        internal static string DataWasLoadedSuccessfully {
            get {
                return ResourceManager.GetString("DataWasLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat.
        /// </summary>
        internal static string DatExtension {
            get {
                return ResourceManager.GetString("DatExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultIcon.
        /// </summary>
        internal static string DefaultIcon {
            get {
                return ResourceManager.GetString("DefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string DefaultIconFormat {
            get {
                return ResourceManager.GetString("DefaultIconFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting key &apos;{0}&apos;.
        /// </summary>
        internal static string DeletingKey {
            get {
                return ResourceManager.GetString("DeletingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to Excel.
        /// </summary>
        internal static string ExportingToExcel {
            get {
                return ResourceManager.GetString("ExportingToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to file &apos;{0}&apos;.
        /// </summary>
        internal static string ExportingToFile {
            get {
                return ResourceManager.GetString("ExportingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel was finished successfully.
        /// </summary>
        internal static string ExportToExcelWasFinishedSuccessfully {
            get {
                return ResourceManager.GetString("ExportToExcelWasFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file was finished successfully.
        /// </summary>
        internal static string ExportToFileWasFinishedSuccessfully {
            get {
                return ResourceManager.GetString("ExportToFileWasFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ExtensionsSeparator {
            get {
                return ResourceManager.GetString("ExtensionsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось очистить список последних файлов. {0}.
        /// </summary>
        internal static string FailedToClearRecentFilesList {
            get {
                return ResourceManager.GetString("FailedToClearRecentFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить файл в списке недавно открытых. {0}.
        /// </summary>
        internal static string FailedToSaveFileInRecentFilesList {
            get {
                return ResourceManager.GetString("FailedToSaveFileInRecentFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show exception window.
        /// </summary>
        internal static string FailedToShowExceptionWindow {
            get {
                return ResourceManager.GetString("FailedToShowExceptionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.ico.
        /// </summary>
        internal static string FileIcon {
            get {
                return ResourceManager.GetString("FileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting value of key &apos;{0}&apos; with name &apos;{1}&apos;.
        /// </summary>
        internal static string GettingKeyValue {
            get {
                return ResourceManager.GetString("GettingKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got data properties: {0}.
        /// </summary>
        internal static string GotDataProperties {
            get {
                return ResourceManager.GetString("GotDataProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got file &apos;{0}&apos; from command line.
        /// </summary>
        internal static string GotFileFromCommandLine {
            get {
                return ResourceManager.GetString("GotFileFromCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got value &apos;{0}&apos;.
        /// </summary>
        internal static string GotValue {
            get {
                return ResourceManager.GetString("GotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hex.
        /// </summary>
        internal static string HexExtension {
            get {
                return ResourceManager.GetString("HexExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X{0}.
        /// </summary>
        internal static string HumanArgumentMultipleColumnTitle {
            get {
                return ResourceManager.GetString("HumanArgumentMultipleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string HumanArgumentSingleColumnTitle {
            get {
                return ResourceManager.GetString("HumanArgumentSingleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y{0}.
        /// </summary>
        internal static string HumanFunctionMultipleColumnTitle {
            get {
                return ResourceManager.GetString("HumanFunctionMultipleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string HumanFunctiontSingleColumnTitle {
            get {
                return ResourceManager.GetString("HumanFunctiontSingleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} bytes while {1} was expected.
        /// </summary>
        internal static string InsufficientBytesRead {
            get {
                return ResourceManager.GetString("InsufficientBytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; already exists in the buffer.
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item{0}.
        /// </summary>
        internal static string ItemValueName {
            get {
                return ResourceManager.GetString("ItemValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string KeyNotExists {
            get {
                return ResourceManager.GetString("KeyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of key &apos;{0}&apos; is null or empty.
        /// </summary>
        internal static string KeyValueIsNullOrEmpty {
            get {
                return ResourceManager.GetString("KeyValueIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings.
        /// </summary>
        internal static string LoadingSettings {
            get {
                return ResourceManager.GetString("LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [X{0}].
        /// </summary>
        internal static string MachineArgumentMultipleColumnTitle {
            get {
                return ResourceManager.GetString("MachineArgumentMultipleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [X].
        /// </summary>
        internal static string MachineArgumentSingleColumnTitle {
            get {
                return ResourceManager.GetString("MachineArgumentSingleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Y{0}].
        /// </summary>
        internal static string MachineFunctionMultipleColumnTitle {
            get {
                return ResourceManager.GetString("MachineFunctionMultipleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Y].
        /// </summary>
        internal static string MachineFunctionSingleColumnTitle {
            get {
                return ResourceManager.GetString("MachineFunctionSingleColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer needs to be shrunk.
        /// </summary>
        internal static string NeedToShrunkBuffer {
            get {
                return ResourceManager.GetString("NeedToShrunkBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item duplicates the last one in the buffer.
        /// </summary>
        internal static string NewItemDuplicatesTheLastOne {
            get {
                return ResourceManager.GetString("NewItemDuplicatesTheLastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer doesn&apos;t exist in the registry.
        /// </summary>
        internal static string NoBufferInRegistry {
            get {
                return ResourceManager.GetString("NoBufferInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data properties. Opening was canceled..
        /// </summary>
        internal static string NoDataPropertiesOpeningCanceled {
            get {
                return ResourceManager.GetString("NoDataPropertiesOpeningCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t exist.
        /// </summary>
        internal static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; &quot;%1&quot;.
        /// </summary>
        internal static string OpenCommandFormat {
            get {
                return ResourceManager.GetString("OpenCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open command is &apos;{0}&apos;.
        /// </summary>
        internal static string OpenCommandIs {
            get {
                return ResourceManager.GetString("OpenCommandIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shell\open\command.
        /// </summary>
        internal static string OpenCommandPath {
            get {
                return ResourceManager.GetString("OpenCommandPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningFile {
            get {
                return ResourceManager.GetString("OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening key &apos;{0}&apos; as read-only.
        /// </summary>
        internal static string OpeningKeyReadOnly {
            get {
                return ResourceManager.GetString("OpeningKeyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.Net.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string RecentFileDtoToStringFormat {
            get {
                return ResourceManager.GetString("RecentFileDtoToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no extensions.
        /// </summary>
        internal static string RegistrySettingsNoExtensions {
            get {
                return ResourceManager.GetString("RegistrySettingsNoExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading file &apos;{0}&apos; with data properties model: {1}.
        /// </summary>
        internal static string ReloadingFileWithDataPropertiesModel {
            get {
                return ResourceManager.GetString("ReloadingFileWithDataPropertiesModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading file &apos;{0}&apos; with new data properties &apos;{1}&apos;.
        /// </summary>
        internal static string ReloadingFileWithNewDataProperties {
            get {
                return ResourceManager.GetString("ReloadingFileWithNewDataProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing association.
        /// </summary>
        internal static string RemovingAssociation {
            get {
                return ResourceManager.GetString("RemovingAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing duplicated item.
        /// </summary>
        internal static string RemovingDuplicatedItem {
            get {
                return ResourceManager.GetString("RemovingDuplicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving item.
        /// </summary>
        internal static string SavingItem {
            get {
                return ResourceManager.GetString("SavingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleString.
        /// </summary>
        internal static string ScaleDtoDisplayMember {
            get {
                return ResourceManager.GetString("ScaleDtoDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2^{0}.
        /// </summary>
        internal static string ScaleDtoScaleStringFormat {
            get {
                return ResourceManager.GetString("ScaleDtoScaleStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string ScaleDtoValueMember {
            get {
                return ResourceManager.GetString("ScaleDtoValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending shell notification.
        /// </summary>
        internal static string SendingShellNotification {
            get {
                return ResourceManager.GetString("SendingShellNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting list of items.
        /// </summary>
        internal static string SettingItems {
            get {
                return ResourceManager.GetString("SettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting value of key &apos;{0}&apos; with name &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        internal static string SettingKeyValue {
            get {
                return ResourceManager.GetString("SettingKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting opening program to &apos;{0}&apos;.
        /// </summary>
        internal static string SettingOpeningProgram {
            get {
                return ResourceManager.GetString("SettingOpeningProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings loading finished.
        /// </summary>
        internal static string SettingsLoadingFinished {
            get {
                return ResourceManager.GetString("SettingsLoadingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxAbsoluteScalePower = {0}, ExportValuesSeparator = &quot;{1}&quot;, RecentFilesCount = {2} RegisteredExtensions = {3}.
        /// </summary>
        internal static string SettingsStorageToStringFormat {
            get {
                return ResourceManager.GetString("SettingsStorageToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrinking buffer to {0} items.
        /// </summary>
        internal static string ShrinkingBuffer {
            get {
                return ResourceManager.GetString("ShrinkingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Classes\{0}\.
        /// </summary>
        internal static string SoftwareClasses {
            get {
                return ResourceManager.GetString("SoftwareClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\{0}\RecentFiles.
        /// </summary>
        internal static string SoftwareRecentFiles {
            get {
                return ResourceManager.GetString("SoftwareRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controlToSendTo.
        /// </summary>
        internal static string SyncContextControlToSendToField {
            get {
                return ResourceManager.GetString("SyncContextControlToSendToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current buffer size is zero.
        /// </summary>
        internal static string ZeroBufferSize {
            get {
                return ResourceManager.GetString("ZeroBufferSize", resourceCulture);
            }
        }
    }
}
