//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTable.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTable.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество масштабов аргументов не соответствует количеству аргументов.
        /// </summary>
        internal static string ArgumentScalesCountMismatch {
            get {
                return ResourceManager.GetString("ArgumentScalesCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дробная.
        /// </summary>
        internal static string ArithmeticTypeFractional {
            get {
                return ResourceManager.GetString("ArithmeticTypeFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целочисленная.
        /// </summary>
        internal static string ArithmeticTypeInteger {
            get {
                return ResourceManager.GetString("ArithmeticTypeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка данных: {0}..
        /// </summary>
        internal static string DataErrorMessage {
            get {
                return ResourceManager.GetString("DataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных не удалась: {0}..
        /// </summary>
        internal static string DataLoadingFailedMessage {
            get {
                return ResourceManager.GetString("DataLoadingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Excel....
        /// </summary>
        internal static string ExportingToExcelStatus {
            get {
                return ResourceManager.GetString("ExportingToExcelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в файл....
        /// </summary>
        internal static string ExportingToFileStatus {
            get {
                return ResourceManager.GetString("ExportingToFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Excel не удался: {0}.
        /// </summary>
        internal static string ExportToExcelFailedMessage {
            get {
                return ResourceManager.GetString("ExportToExcelFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в файл не удался: {0}..
        /// </summary>
        internal static string ExportToFileFailedMessage {
            get {
                return ResourceManager.GetString("ExportToFileFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в файл успешно завершен..
        /// </summary>
        internal static string ExportToFileSucceededMessage {
            get {
                return ResourceManager.GetString("ExportToFileSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать или открыть ключ &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToCreateOrOpenKey {
            get {
                return ResourceManager.GetString("FailedToCreateOrOpenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список последних файлов: {0}.
        /// </summary>
        internal static string FailedToLoadRecentFiles {
            get {
                return ResourceManager.GetString("FailedToLoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить файл в списке недавно открытых. {0}.
        /// </summary>
        internal static string FailedToSaveFileInRecentFilesList {
            get {
                return ResourceManager.GetString("FailedToSaveFileInRecentFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; не существует..
        /// </summary>
        internal static string FileNotExistsExceptionMessage {
            get {
                return ResourceManager.GetString("FileNotExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бинарный файл DataTable.Net.
        /// </summary>
        internal static string FileTypeDescription {
            get {
                return ResourceManager.GetString("FileTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество масштабов функции не соответствует количеству функций.
        /// </summary>
        internal static string FunctionScalesCountMismatch {
            get {
                return ResourceManager.GetString("FunctionScalesCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string InformationMessageTitle {
            get {
                return ResourceManager.GetString("InformationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла....
        /// </summary>
        internal static string LoadingFileStatus {
            get {
                return ResourceManager.GetString("LoadingFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек....
        /// </summary>
        internal static string LoadingSettingsStatus {
            get {
                return ResourceManager.GetString("LoadingSettingsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно освободить ссылку, поскольку счетчик равен нулю.
        /// </summary>
        internal static string NoReferencesToRelease {
            get {
                return ResourceManager.GetString("NoReferencesToRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при: прочитано {0} байт, когда ожидалось {1}..
        /// </summary>
        internal static string ReadFromFileExceptionMessage {
            get {
                return ResourceManager.GetString("ReadFromFileExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить настройки: {0}.
        /// </summary>
        internal static string SaveSettingsFailed {
            get {
                return ResourceManager.GetString("SaveSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение настроек.
        /// </summary>
        internal static string SavingSettingsStatus {
            get {
                return ResourceManager.GetString("SavingSettingsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка настроек не удалась: {0}.
        /// </summary>
        internal static string SettingsLoadingFailedMessage {
            get {
                return ResourceManager.GetString("SettingsLoadingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия: {1}{0}Дата сборки: {2}.
        /// </summary>
        internal static string VersionInfoFormat {
            get {
                return ResourceManager.GetString("VersionInfoFormat", resourceCulture);
            }
        }
    }
}
